config/routes.rb
Rails.application.routes.draw do
  

  resources :question_types, except: [:show]
  resources :topics, except: [:show]
  resources :categories, except: [:show]
  devise_for :users

  root 'home#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :category
  validates :name, :category_id, presence: true

  def get_category
    return self.category.name
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  add_breadcrumb "Home", :root_path
  before_filter :authenticate_user!
  before_action :set_topic, only: [:edit, :update, :destroy]
  before_action :get_categories, only: [:new, :create, :edit, :update]


  # GET /topics
  # GET /topics.json
  def index
    topic_breadcrums({})
    @topics = Topic.all
  end

  # GET /topics/new
  def new
    topic_breadcrums({"display_text": "New Topic"})
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
    topic_breadcrums({"display_text": "Edit Topic"})
  end

  # POST /topics
  # POST /topics.json
  def create
    topic_breadcrums({"display_text": "Create Topic"})
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_url, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    topic_breadcrums({"display_text": "Update Topic"})
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topics_url, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_topic
    @topic = Topic.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def topic_params
    params.require(:topic).permit(:category_id, :name)
  end

  def topic_breadcrums(breadcrums_data)
    add_breadcrumb "Topics", :topics_path
    if breadcrums_data.present?
      add_breadcrumb breadcrums_data[:display_text]
    end
  end

  def get_categories
    @categories = Category.all
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic, html: { role: "form" } ) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :category_id %><br>
    <%= collection_select(:topic, :category_id, @categories, :id, :name, {prompt: true}, {required: true}) %>
  </div>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, required: true %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary"  %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing Topics</h1>

<table id="topics" class="display" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Category</th>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th>Category</th>
      <th>Name</th>
      <th></th>
    </tr>
  </tfoot>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.get_category %></td>
        <td><%= topic.name %></td>
        <td>
            <%= link_to 'Edit', edit_topic_path(topic), class: "btn btn-primary"  %>
            <%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>

<%= link_to 'New Topic', new_topic_path %>
<script>
  $(document).ready(function() {
    $('#topics').DataTable();
  });

</script>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>