config/routes.rb
Rails.application.routes.draw do
  

  resources :question_types, except: [:show]
  resources :topics, except: [:show]
  resources :categories, except: [:show]
  devise_for :users

  root 'home#index'

end

app/controllers/question_types_controller.rb
class QuestionTypesController < ApplicationController
  before_action :set_question_type, only: [:edit, :update, :destroy]
  add_breadcrumb "Home", :root_path

  # GET /question_types
  # GET /question_types.json
  def index
    question_type_breadcrums({})
    @question_types = QuestionType.all
  end

  # GET /question_types/new
  def new
    question_type_breadcrums({"display_text": "New Question type"})
    @question_type = QuestionType.new
  end

  # GET /question_types/1/edit
  def edit
    question_type_breadcrums({"display_text": "Edit Question type"})
  end

  # POST /question_types
  # POST /question_types.json
  def create
    question_type_breadcrums({"display_text": "Create Question type"})
    @question_type = QuestionType.new(question_type_params)

    respond_to do |format|
      if @question_type.save
        format.html { redirect_to question_types_url, notice: 'Question type was successfully created.' }
        format.json { render :index, status: :created, location: @question_type }
      else
        format.html { render :new }
        format.json { render json: @question_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /question_types/1
  # PATCH/PUT /question_types/1.json
  def update
    question_type_breadcrums({"display_text": "Update Question type"})
    respond_to do |format|
      if @question_type.update(question_type_params)
        format.html { redirect_to question_types_url, notice: 'Question type was successfully updated.' }
        format.json { render :index, status: :ok, location: @question_type }
      else
        format.html { render :edit }
        format.json { render json: @question_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_types/1
  # DELETE /question_types/1.json
  def destroy
    @question_type.destroy
    respond_to do |format|
      format.html { redirect_to question_types_url, notice: 'Question type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_type
      @question_type = QuestionType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_type_params
      params.require(:question_type).permit(:name)
    end

    def question_type_breadcrums(breadcrums_data)
      add_breadcrumb "Question Types", :question_types_path
      if breadcrums_data.present?
        add_breadcrumb breadcrums_data[:display_text]
      end
    end

end

app/helpers/question_types_helper.rb
module QuestionTypesHelper
end

app/views/question_types/_form.html.erb
<%= form_for(@question_type , html: { role: "form" } ) do |f| %>
  <% if @question_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question_type.errors.count, "error") %> prohibited this question_type from being saved:</h2>

      <ul>
      <% @question_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, required: true  %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/question_types/edit.html.erb
<h1>Editing Question Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @question_type %> |
<%= link_to 'Back', question_types_path %>

app/views/question_types/index.html.erb
<h1>Listing Question Types</h1>

<table id="question_types" class="display" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </tfoot>
  <tbody>
    <% @question_types.each do |question_type| %>
      <tr>
        <td><%= question_type.name %></td>
        <td>
            <%= link_to 'Edit', edit_question_type_path(question_type), class: "btn btn-primary" %>
            <%= link_to 'Destroy', question_type, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question type', new_question_type_path %>
<script>
  $(document).ready(function() {
    $('#categories').DataTable();
  });

</script>

app/views/question_types/new.html.erb
<h1>New Question Type</h1>

<%= render 'form' %>

<%= link_to 'Back', question_types_path %>