config/routes.rb
Rails.application.routes.draw do
  

  resources :question_types, except: [:show]
  resources :topics, except: [:show]
  resources :categories, except: [:show]
  devise_for :users

  root 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Questionnaire</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'Questionnaire', root_path, class: 'navbar-brand' %>
        </div>
        <div id="navbar">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Home', root_path %></li>
            <% if user_signed_in? %>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  Manage
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to 'Categories', categories_path %></li>
                  <li><%= link_to 'Topics', topics_path %></li>
                  <li><%= link_to 'Question Type', question_types_path %></li>
                </ul>
              </li>
              
            <% end %>
          </ul>
          <ul class="nav navbar-nav pull-right">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  <%= current_user.name %>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to 'Profile', edit_user_registration_path %></li>
                  <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to 'Log In', new_user_session_path %></li>
              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    
    <div class="container">
      <%= render_breadcrumbs %>
      <% if notice %>
        <p class="alert alert-success alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= alert %>
        </p>
      <% end %>
      <%= yield :top_content %>
      <h1><%= yield :header %></h1>
      <%= yield %>
    </div>




  </body>
  </html>